### PR TITLE
Drop travis, use github actions

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by wpoely86** [comment]
as actions only run after a merge (for the first time): https://github.com/wpoely86/logstash-patterns/runs/1730486215

**Comment by wpoely86** [comment]
@itkovian please have a look. I don't know why jenkins is failing as it is working well on my end.

**Comment by stdweird** [comment]
@wpoely86 the error is due to not using vsc-install and the way our jenkins is setup. you need to write something similar to https://github.com/hpcugent/vsc-accountpage/commit/76eee9448bcb94de0454f2620123492e0ce18fa4
the actual error is
```
xception:

Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main

    status = self.run(options, args)

  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run

    strip_file_prefix=options.strip_file_prefix,

  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install

    **kwargs

  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install

    strip_file_prefix=strip_file_prefix

  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files

    strip_file_prefix=strip_file_prefix,

  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 247, in move_wheel_files

    prefix=prefix,

  File "/usr/lib/python3.6/site-packages/pip/locations.py", line 153, in distutils_scheme

    i.finalize_options()

  File "/usr/lib64/python3.6/distutils/command/install.py", line 329, in finalize_options

    self.create_home_path()

  File "/usr/lib64/python3.6/distutils/command/install.py", line 548, in create_home_path

    os.makedirs(path, 0o700)

  File "/usr/lib64/python3.6/os.py", line 210, in makedirs

    makedirs(head, mode, exist_ok)

  File "/usr/lib64/python3.6/os.py", line 210, in makedirs

    makedirs(head, mode, exist_ok)

  File "/usr/lib64/python3.6/os.py", line 220, in makedirs

    mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: '/var/lib/jenkins/.local/lib'

script returned exit code 2
```

**Comment by wpoely86** [comment]
@stdweird I think I adjusted it correctly but it still fails. Could you share the output of jenkins again please?

**Comment by boegel** [comment]
@wpoely86 The problem is still the same:

```
PermissionError: [Errno 13] Permission denied: '/var/lib/jenkins/.local/lib'
```

This is because we've changed permissions on `$HOME/.local` on our Jenkins system to prevent Python packages from being installed with `--user`, since that makes them "global" across all repos, and it opens the door to let Jenkins jobs running at the same time to step on each others toes.

That's fixed with the changes you're making in the `Jenkinsfile`, but since you don't have full access to this repo the tests on Jenkins are being run with the `Jenkinsfile` that's in `master` (since you're not "trusted", by Jenkins).

I'll open a separate PR with the fixes for `Jenkinsfile` that should remedy this, once it gets merged and you rebase this PR.

**Comment by boegel** [comment]
@wpoely86 fixed in #48, please rebase

**Comment by wpoely86** [comment]
@boegel green!

**Pull request merged**
